# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a512977f39fd8ab883287ed245466b74759edabfc252bfb8b9366065ab36b638236909d075e0c5a07513727fc2885fcc6bc64897f3dd04df02247f2c994ae307

test:
  secret_key_base: 54687317fb0e8fc60a22d3204003027cdc473c1b1a75e1c74c667b502334dd8a268a352a5d623fce431f42ba4b105b4bafaa1f3ede20a4e6452b8470a6fd7d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
